### ISSUE TITLE
Definizione pacchetto di aggiornamento

### ISSUE THREAD

**Issue by fgalfa** [alfa-sw/sw-programmazione-schede#11]
Allo scopo di permettere un aggiornamento complessivo di tutte le schede di una macchina, è utile definire un pacchetto di aggiornamento, che consiste nell'insieme di:
- programmi da flashare;
- documento strutturato contenente i dettagli dell'aggiornamento: quali nodi aggiornare, quale file aggiornare su ciascun nodo, eventuali prerequisiti sulle versioni preesistenti.

Il pacchetto potrebbe essere un archivio compresso che viene distribuito assieme agli aggiornamenti della scheda master.
L'utente dovrà specificare solo quale pacchetto caricare e far partire l'aggiornamento,
Anche in fase di preparazione della macchina l'operatore sceglie il pacchetto e aggiorna l'intera macchina. Non ci sarà quindi più bisogno di usare l'attuale interfaccia grafica.

Usiamo questa issue per discutere di questo argomento.

**Comment by micheleabelli** [comment]
A seguito della riunione di oggi 5.11.2021,
presenti: Michele, Marco, Filippo
abbiamo fissato alcune idee e strategie da condividere ed evolvere con il Software:
- - - - - - - - - - - -
L’ufficio tecnico creerà un pacchetto di aggiornamento FW (archivio compresso) contenente tutti i possibili file eseguibili di una determinata macchina, ed un file editabile con le istruzioni di aggiornamento. 
L’aggiornatore leggerà innanzitutto la configurazione macchina attraverso il comando seriale specifico, ottenendo quindi l’informazione di quali schede Slave sono abilitate e quindi da aggiornare. 
Questa attività si potrebbe concretizzare ogniqualvolta una nuova versione di FW ufficiale verrà rilasciata.
 Ci saranno 3 tipi di pacchetti distinti per tipologia di macchina:
-	CRX e THOR 2.0
-	DESK e COLOR LAB
-	CT 2.0 e CT 3.0

L’aggiornatore dovrebbe ottenere l’informazione del tipo di macchina su cui lavorare dai Software applicativi (ad es.Alfa40).
Attraverso una procedura da definire, in prima battuta analoga a quella utilizzata per scaricare gli aggiornamenti SW sul Raspberry, si scaricheranno i pacchetti di aggiornamento FW sulle macchine in campo che sono raggiungibili da remoto.
Si ragionerà sulla possibilità di usare ‘AlfaCloud’ per questa attività che andrà resa automatica nel momento stesso in cui verranno pubblicati pacchetti di aggiornamento.
Dovrà essere possibile eseguire l’aggiornamento anche a livello locale mettendo i pacchetti di aggiornamento in una chiavetta usb collegabile al Raspberry.

Durante la procedura di aggiornamento potrebbero verificarsi eventi avversi:
-	Salto al Boot non avvenuto correttamente: in tal caso attraverso la seriale 232 si andranno a leggere codici di errore specifici che poi andranno inoltrati ad ‘Alfa40’
-	Aggiornamento FW non avvenuto correttamente. In tal caso l’attività di ‘Verifica’ fallisce. L’aggiornatore riproverà max 3 volte prima di segnalare ad ‘Alfa40’ che l’aggiornamento è fallito

‘Alfa40’ segnalerà all’operatore che sono disponibili degli aggiornamenti FW.
L’attività di aggiornamento partirà quando un operatore premerà un pulsante di ‘FW UPDATE’ (l’aggiornamento non partirà in automatico). 
Dato il livello di conoscenze tecniche di basso profilo, all’operatore andranno segnalate poche ed essenziali informazioni, ad es.‘FW UPDATE SUCCESSFULL’ e ‘FW UPDATE FAILED’.
Una semplice barra di aggiornamento incrementale potrebbe segnalare che l’attività sta procedendo.

Sulla scheda Raspberry saranno sempre presenti i 2 pacchetti di aggiornamento più recenti caricati in macchina.

L’aggiornatore potrà essere utilizzato anche in produzione, ossia per caricare il FW su macchine che hanno solo il Bootloader.

Sulle le macchine in campo che richiederanno questo nuovo servizio dovrà essere aggiornato (a mano) il Bootloader su tutte le schede configurate.

 Il servizio di aggiornamento FW da remoto dovrebbe essere a pagamento verso i clienti che lo richiederanno.

Qualora una macchina non avesse il cavo USB collegato alla scheda MMT / MAB il salto al Bootloader non sarà possibile e verrà generato un codice di errore. Per permettere le funzionalità di aggiornamento occorrerà collegare il cavo e riaccendere la macchina.

**Comment by fgalfa** [comment]
Questo è un possibile schema del file descrittore del pacchetto, in formato YAML (nessun problema a usare JSON se lo si preferisce).

```
machine-family: CR6                 # nome della famiglia di macchine a cui si applica
                                    # l'aggiornamento; l'aggiornatore deve recuperare
                                    # questa informazione da un file di configurazione
                                    # o dal SW su scheda linux
programs:
   - board-name: mab
     filename: mab_2.2.2.hex        # il nome del file HEX - facoltativo, si può anche 
                                    # scegliere di usare sempre lo stesso nome
     version: 2.2.2                 # il numero di versione dell'applicativo da aggiornare
     boot-version-requisite: 1.0.0  # versione di boot minima per fare l'aggiornamento
     addresses: [255]               # indirizzi coinvolti nell'aggiornamento
                                    # da intersecare con la lista degli indirizzi abilitati
                                    # fornita da READ_SLAVES_CONFIGURATION
     release-date: 2021-11-08
     checksum: 0x325312             # dobbiamo scegliere una funzione hash: checksum
                                    # MD5 ecc; checksum è facile da calcolare lato FW
   - board-name: sccb
     filename: sccb_1.0.4.hex   
     version: 1.0.4
     boot-version-requisite: 1.0.0
     addresses: [1, 2, 4, 6]
     release-date: 2021-11-08

```
